- name: Check if Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: homebrew_installed

- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not homebrew_installed.stat.exists

- name: Tap Homebrew/cask if not tapped
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - tmux
    - wireshark
    - fzf
    - tldr
    - ripgrep
    - yabai
  tags:
    - install
    - productivity

- name: Install GUI applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - gimp
    - kdenlive
  tags:
    - install
    - productivity
