- hosts: localhost
  pre_tasks:
    - name: Update Homebrew
      command: brew update
      tags:
        - install
        - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/npm-packages.yml
