- name: Install System Packages 1 (cmake, pkg-config)
  homebrew:
    name: ["cmake", "pkg-config"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, gettext)
  homebrew:
    name: ["lua@5.1", "unzip", "libtool", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  homebrew:
    name:
      [
        "yabai",
        "curl",
        "htop",
        "go",
        "lsof",
        "ccache",
        "ninja",
        "python@3.9",
        "moreutils",
        "llvm",
      ]
  tags:
    - install
    - core

- name: Install Clang
  homebrew:
    name: ["llvm"]
  tags:
    - install
    - neovim
    - core
