- name: Remove neovim
  ansible.builtin.command:
    cmd: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Get Packer
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/Nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  ansible.builtin.command:
    cmd: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - install
    - neovim

- name: Install neovim
  ansible.builtin.command:
    cmd: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 1
  homebrew:
    name: luarocks
  tags:
    - install
    - neovim

- name: Neovim Plugin Development 2 luacheck
  ansible.builtin.command:
    cmd: luarocks install luacheck
  tags:
    - install
    - neovim
